name: fernand_envlrp
channels:
  - conda-forge
dependencies:
  - cartopy
  - pandas
  - regionmask
  - dask
  - seaborn
  - matplotlib
  - jupyter
  - python=3.6
  - scikit-learn
  - xarray
  - jupytext
  - tensorflow==1.15
  - geopandas
  - jupyterlab
  - keras
  - netcdf4
